### ISSUE TITLE
name power is not defined

### ISSUE THREAD

**Issue by martmists** [dgorissen/pycel#39]
```python
>>> excel.evaluate("Sheet1!A27")
Traceback (most recent call last):
  File "X:\Python\lib\site-packages\pycel\excelformula.py", line 801, in eval_func
    ret_val = excel_formula.compiled_lambda()
  File "X:\Python\lib\site-packages\pycel\excelformula.py", line 818, in <lambda>
    ### Traceback will show this line if not loaded from a text file
NameError: name 'power' is not defined
Eval: sqrt(power(_C_("Sheet1!F37"), 2) + power(_C_("Sheet1!G37"), 2))
Traceback (most recent call last):
  File "X:\Python\lib\site-packages\pycel\excelformula.py", line 801, in eval_func
    ret_val = excel_formula.compiled_lambda()
  File "X:\Python\lib\site-packages\pycel\excelformula.py", line 818, in <lambda>
    ### Traceback will show this line if not loaded from a text file
NameError: name 'power' is not defined

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "X:\Python\lib\site-packages\pycel\excelformula.py", line 801, in eval_func
    ret_val = excel_formula.compiled_lambda()
  File "X:\Python\lib\site-packages\pycel\excelformula.py", line 818, in <lambda>
    ### Traceback will show this line if not loaded from a text file
  File "X:\Python\lib\site-packages\pycel\excelcompiler.py", line 619, in _evaluate
    value = self.eval(cell.formula)
  File "X:\Python\lib\site-packages\pycel\excelformula.py", line 805, in eval_func
    exc=FormulaEvalError)
  File "X:\Python\lib\site-packages\pycel\excelformula.py", line 749, in error_logger
    raise exc(error_msg)
pycel.excelformula.FormulaEvalError: Traceback (most recent call last):
  File "X:\Python\lib\site-packages\pycel\excelformula.py", line 801, in eval_func
    ret_val = excel_formula.compiled_lambda()
  File "X:\Python\lib\site-packages\pycel\excelformula.py", line 818, in <lambda>
    ### Traceback will show this line if not loaded from a text file
NameError: name 'power' is not defined
Eval: sqrt(power(_C_("Sheet1!F37"), 2) + power(_C_("Sheet1!G37"), 2))
Eval: xif(abs(_C_("Sheet1!H37")) < abs(_C_("Sheet1!C37")), 1, 0)
Traceback (most recent call last):
  File "X:\Python\lib\site-packages\pycel\excelformula.py", line 801, in eval_func
    ret_val = excel_formula.compiled_lambda()
  File "X:\Python\lib\site-packages\pycel\excelformula.py", line 818, in <lambda>
    ### Traceback will show this line if not loaded from a text file
NameError: name 'power' is not defined
```

**Comment by martmists** [comment]
After a bit of testing, the same happens with `xor`
