### ISSUE TITLE
While Process a large xlsx , get  'ReadOnlyWorksheet' object has no attribute 'iter_cols' from Openpyxl

### ISSUE THREAD

**Issue by ftune** [dgorissen/pycel#42]
I got a large xlsx file (621KB) and many excel formulas(mid/vlookup/or something) cross using in it .
Tried to run the example code, and got error msg like:
```
Traceback (most recent call last):

  File "<ipython-input-1-d87f46d59f95>", line 1, in <module>
    runfile('C:/Users/Administrator/Desktop/file/example2.py', wdir='C:/Users/Administrator/Desktop/file')

  File "d:\ProgramData\Anaconda3\lib\site-packages\spyder\utils\site\sitecustomize.py", line 705, in runfile
    execfile(filename, namespace)

  File "d:\ProgramData\Anaconda3\lib\site-packages\spyder\utils\site\sitecustomize.py", line 102, in execfile
    exec(compile(f.read(), filename, 'exec'), namespace)

  File "C:/Users/Administrator/Desktop/file/example2.py", line 34, in <module>
    print("D1 is %s" % excel.evaluate('S1!C60'))

  File "d:\ProgramData\Anaconda3\lib\site-packages\pycel-1.0b5-py3.6.egg\pycel\excelcompiler.py", line 652, in evaluate
    self._gen_graph(address)

  File "d:\ProgramData\Anaconda3\lib\site-packages\pycel-1.0b5-py3.6.egg\pycel\excelcompiler.py", line 685, in _gen_graph
    self._process_gen_graph()

  File "d:\ProgramData\Anaconda3\lib\site-packages\pycel-1.0b5-py3.6.egg\pycel\excelcompiler.py", line 697, in _process_gen_graph
    self._gen_graph(precedent_address, recursed=True)

  File "d:\ProgramData\Anaconda3\lib\site-packages\pycel-1.0b5-py3.6.egg\pycel\excelcompiler.py", line 681, in _gen_graph
    self._make_cells(seed)

  File "d:\ProgramData\Anaconda3\lib\site-packages\pycel-1.0b5-py3.6.egg\pycel\excelcompiler.py", line 572, in _make_cells
    new_cells = build_range(address)

  File "d:\ProgramData\Anaconda3\lib\site-packages\pycel-1.0b5-py3.6.egg\pycel\excelcompiler.py", line 551, in build_range
    excel_range = self.excel.get_range(rng)

  File "d:\ProgramData\Anaconda3\lib\site-packages\pycel-1.0b5-py3.6.egg\pycel\excelwrapper.py", line 186, in get_range
    cells_dataonly = sheet_dataonly[address.coordinate]

  File "d:\ProgramData\Anaconda3\lib\site-packages\openpyxl\worksheet\_read_only.py", line 41, in __getitem__
    return meth(key)

  File "d:\ProgramData\Anaconda3\lib\site-packages\openpyxl\worksheet\worksheet.py", line 292, in __getitem__
    cols = tuple(self.iter_cols(min_col, max_col))

AttributeError: 'ReadOnlyWorksheet' object has no attribute 'iter_cols'
```

Which might be caused by readonly mode in openpyxl.
How to fix this? Say, turn to writeonly mode?
All the calculation has been set up using the MS Excel interface ,I just want to try change some numbers and regenerate the particular Cells to get the output. I.E. to use the xlsx file as a calculate engine.
I might try to edit the xlsx data and use win32com to open the xlsx file and refresh the output cell, But it is a little slow rather than 50ms.
Any suggestions?

**Comment by stephenrauch** [comment]
A very curious error.  But essentially impossible to debug without access to the spreadsheet.

**Comment by stephenrauch** [comment]
Googling this error: 

```
AttributeError: 'ReadOnlyWorksheet' object has no attribute 'iter_cols'
```

from the stack trace you provided, ended up finding [a closed as invalid openpyxl bug](https://bitbucket.org/openpyxl/openpyxl/issues/889/attributeerror-readonlyworksheet-object) which was due to the statement:

```
worksheet['A']
```
Which asks for an entire column, and ends up being translated by openpyxl to a call to `itercols`.  Pycel can make similar calls for formulas references like:

```
Sheet1!A:A
```

Challenge here is that Pycel is not explicitly calling `worksheet['A']` is is simply trying to evaluate a formula.  The "fix" here is to monkey patch an `iter_cols()` onto the read_only worksheet.
