### ISSUE TITLE
LINEST function fails w/ Workbook created in LibreOffice

### ISSUE THREAD

**Issue by henrus** [dgorissen/pycel#97]
Hi,
thanks for this piece of software!

#### Problem description

Execution of LINEST function crashes. Simple test case attached.

#### What actually happened

Loading test2.xlsx...
Traceback (most recent call last):
  File "compileExcel4.py", line 12, in <module>
    print("D1 is {}".format(excel.evaluate('Sheet1!D1')))
  File "/usr/local/lib/python3.5/dist-packages/pycel/excelcompiler.py", line 806, in _evaluate_non_iterative
    self._gen_graph(address)
  File "/usr/local/lib/python3.5/dist-packages/pycel/excelcompiler.py", line 875, in _gen_graph
    self._process_gen_graph()
  File "/usr/local/lib/python3.5/dist-packages/pycel/excelcompiler.py", line 887, in _process_gen_graph
    self._gen_graph(precedent_address, recursed=True)
  File "/usr/local/lib/python3.5/dist-packages/pycel/excelcompiler.py", line 871, in _gen_graph
    self._make_cells(seed)
  File "/usr/local/lib/python3.5/dist-packages/pycel/excelcompiler.py", line 717, in _make_cells
    new_nodes = build_range(excel_data)
  File "/usr/local/lib/python3.5/dist-packages/pycel/excelcompiler.py", line 701, in build_range
    for addr in a_range.needed_addresses:
  File "/usr/local/lib/python3.5/dist-packages/pycel/excelcompiler.py", line 1031, in needed_addresses
    return self.formula and self.formula.needed_addresses or iter(self)
  File "/usr/local/lib/python3.5/dist-packages/pycel/excelformula.py", line 614, in needed_addresses
    if self.python_code:
  File "/usr/local/lib/python3.5/dist-packages/pycel/excelformula.py", line 636, in python_code
    self._python_code = self.ast.emit
  File "/usr/local/lib/python3.5/dist-packages/pycel/excelformula.py", line 442, in emit
    return handler()
  File "/usr/local/lib/python3.5/dist-packages/pycel/excelformula.py", line 481, in func_linest
    degree, coef = get_linest_degree(self.cell)
  File "/usr/local/lib/python3.5/dist-packages/pycel/excelutil.py", line 864, in get_linest_degree
    address.address_at_offset(row_inc=0, col_inc=i))
AttributeError: 'AddressRange' object has no attribute 'address_at_offset'

#### What was expected to happen

D1 is 0.9224

#### Code Sample

The Excel work book contain a few number in A1:B5 and the LINEST-function

{=LINEST(A1:A5,B1:B5)}

It has been created in Libreoffice and saved in xlsx-format. I am happy to provide it.

```python
from pycel import ExcelCompiler

filename = "test2.xlsx"
print("Loading {}...".format(filename))

# load & compile the file to a graph
excel = ExcelCompiler(filename=filename)

#print("Setting B1 to 0.6")
#excel.set_value('Sheet1!B1', 0.6)

print("D1 is {}".format(excel.evaluate('Sheet1!D1')))
```

#### Environment

Pycel 1.0b22, Python 3.5.2 and Ubuntu 16.04.

**Comment by stephenrauch** [comment]
I believe this has been resolved with #122
